[project]
name = "network-security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "certifi>=2026.7.22",
    "dagshub>=0.7.1",
    "fastapi>=0.141.1",
    "mlflow>=3.15.2",
    "numpy>=2.5.2",
    "pandas>=2.3.3",
    "pyaml>=26.7.0",
    "pymongo[srv]>=4.17.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.0",
    "setuptools>=84.0.0",
    "uvicorn>=0.52.4",
]
[tool.setuptools.packages.find]
include = ["networksecurity*"]